export const LOGIN_USER = 'LOGIN_USER';
export const LOGOUT_USER = 'LOGOUT_USER';
export const FETCH_ROUTES_SUCCESS = 'FETCH_ROUTES_SUCCESS';
export const FETCH_ROUTES_PENDING = 'FETCH_ROUTES_PENDING';
export const FETCH_ROUTES_ERROR = 'FETCH_ROUTES_ERROR';

